defaults:
  - default
  - _self_

# Override from `default` config
id: procgen
video_freq: 10
#video_length: 200

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.procgen.ProcgenWrapper
  id: ${env.id}
  seed: ${seed}
  deterministic: True
  num_levels: 1
  distribution_mode: "easy"
  center_agent: True
