# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: procgen
  - _self_

# Experiment
seed: 42

# Environment
env:
  num_envs: 8
  id: bossfight
  num_levels: 1
  deterministic: True
  distribution_mode: "easy"

# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 4096
  total_steps: 10000000
  train_every: 1
  per_rank_sequence_length: 16
  horizon: 8
